docs: hugo version bump to 0.97.2
Coding/coding-download-center pull request #112
Opened 2022-04-18 12:36 UTC by eallion

2022-04-18 13:10 UTC, eallion commented
I sort the index.md by `sort`, but check it fails.

2022-04-18 13:12 UTC, eallion commented
The shell script:
https://gist.github.com/eallion/aaecaec8107912755c4a22681687da30

2022-04-20 03:20 UTC, sinkcup approved these changes

2022-04-20 03:21 UTC, sinkcup requested changes

2022-04-20 03:21 UTC, sinkcup commented on index.md
> -golangci-lint-linux-amd64.tar.gz | 1.43.0 | https://github.com/golangci/golangci-lint/releases/download/v1.43.0/golangci-lint-1.43.0-linux-amd64.tar.gz | f3515cebec926257da703ba0a2b169e4a322c11dc31a8
这个顺序是对的，改了导致 CI 挂了

2022-04-20 03:26 UTC, sinkcup commented
> The shell script: https://gist.github.com/eallion/aaecaec8107912755c4a22681687da30

奇怪，我看看

2022-04-28 14:28 UTC, closed without merging